### ISSUE TITLE
Getting error `path2.basename` is not a function.

### ISSUE THREAD

**Issue by dannysmc95** [Kingwl/monaco-volar#2] opened 2022-07-06 08:42 UTC
Created an example here:
```
<template>
	<div id="container" ref="monacoeditorcontainer"></div>
</template>

<script setup lang="ts">
	import * as onigasm from 'onigasm';
	import onigasmWasm from 'onigasm/lib/onigasm.wasm?url';
	import editorWorker from 'monaco-editor-core/esm/vs/editor/editor.worker?worker';
	import vueWorker from 'monaco-volar/vue.worker?worker';
	import { editor } from 'monaco-editor-core';
	import { loadGrammars, loadTheme, prepareVirtualFiles } from 'monaco-volar';
	import { onMounted, ref } from 'vue';

	const monacoeditorcontainer = ref<HTMLElement | null>(null);
	let editorInstance: unknown;

	const loadOnigasm = async () => onigasm.loadWASM(onigasmWasm);

	const loadMonacoEnv = () => {
		(self as any).MonacoEnvironment = {
			async getWorker(_: any, label: string) {
				if (label === "vue") {
					return new vueWorker();
				}
				return new editorWorker();
			},
		};
	}

	onMounted(() => {
		Promise.all([ loadMonacoEnv(), loadOnigasm(), loadTheme() ]).then(([ , , theme]) => {

			// Check for valid element.
			if (!monacoeditorcontainer.value) return;

			// Prepare the virtual files.
			prepareVirtualFiles();

			// Create the editor.
			const editorInstance = editor.create(monacoeditorcontainer.value, {
				theme,
				language: 'vue',
				automaticLayout: true,
				scrollBeyondLastLine: false,
				minimap: {
					enabled: false,
				},
				inlineSuggest: {
					enabled: false,
				},
				value: '<template>\n\t<div>Hello World</div>\n</template>',
			});

			loadGrammars(editorInstance);
		});
	});
</script>
```

So syntax highlighting seems to work, but I am getting an error:

```
errors.js:12 Uncaught Error: path2.basename is not a function

TypeError: path2.basename is not a function
    at Object.getEmbeddedFile (vue.worker.js?worker_file:210323:38)
    at ReactiveEffect.fn (vue.worker.js?worker_file:210699:68)
    at ReactiveEffect.run (vue.worker.js?worker_file:209603:23)
    at get value [as value] (vue.worker.js?worker_file:209768:39)
    at ReactiveEffect.fn (vue.worker.js?worker_file:210702:26)
    at ReactiveEffect.run (vue.worker.js?worker_file:209603:23)
    at get value [as value] (vue.worker.js?worker_file:209768:39)
    at ReactiveEffect.fn (vue.worker.js?worker_file:210790:26)
    at ReactiveEffect.run (vue.worker.js?worker_file:209603:23)
    at get value [as value] (vue.worker.js?worker_file:209768:39)
    at errors.js:12:27
```

Any ideas?

Tried following the README.md, but it's not very clear, I ended up following your test folder which gave me less errors, but the above is the main error I am seeing now.

Could do with a better example, as the example in `gh-pages` is currently compiled, so can't see what you did to get it working.

**Comment by dannysmc95** [comment] 2022-07-07 16:20
So @johnsoncodehk is that the fix above? Because not sure if this project is maintained but would be happy to contribute to it of course.

**Comment by johnsoncodehk** [comment] 2022-07-08 00:22
You should have correct path-browserify setup to bundle the project, if you can share the project I may able to find out setup problem.

**Comment by dannysmc95** [comment] 2022-07-11 07:39
Just a small note here, I was getting help from @johnsoncodehk and after I added the following to my Vite setup:

```typescript
import 'path-browserify';

export default defineConfig({
    /* ... */
    resolve: {
        alias: {
	    path: "path-browserify",
	},
    },
    /* ... */
});
```

I now get the following error:
```
editorSimpleWorker.js:460 Uncaught (in promise) Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:460:31)
    at webWorker.js:38:30
```

Plus a handful of the below:
```
errors.js:12 Uncaught Error: Unexpected usage

Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:460:31)
    at webWorker.js:38:30
    at errors.js:12:27
```

And finally:
```
index.js?v=41090277:529 Uncaught ReferenceError: module is not defined
    at index.js?v=41090277:529:1
```

Additionally, everytime I type, I get:
```
errors.js:12 Uncaught Error: Unexpected usage

Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:460:31)
    at webWorker.js:38:30
    at errors.js:12:27
```

Hope that helps.

Thanks,

**Comment by Kingwl** [comment] 2022-07-11 08:02
HI! I have tried your demo, please try the following patch. 

In general, it is the `path` that is not handled correctly that is the cause. We will consider bundling it into the package in a later version.

```patch
diff --git a/package.json b/package.json
index 7401ed4..232655a 100644
--- a/package.json
+++ b/package.json
@@ -14,6 +14,7 @@
     "monaco-editor-core": "^0.33.0",
     "monaco-volar": "^0.0.2",
     "onigasm": "^2.2.5",
+    "path-browserify": "^1.0.1",
     "vite-plugin-monaco-editor": "^1.0.10",
     "vue": "^3.2.25"
   },
diff --git a/src/components/Monaco.vue b/src/components/Monaco.vue
index 38abb46..27c2cba 100644
--- a/src/components/Monaco.vue
+++ b/src/components/Monaco.vue
@@ -7,7 +7,7 @@
 	import onigasmWasm from 'onigasm/lib/onigasm.wasm?url';
 	import editorWorker from 'monaco-editor-core/esm/vs/editor/editor.worker?worker';
 	import vueWorker from 'monaco-volar/vue.worker?worker';
-	import { editor } from 'monaco-editor-core';
+	import { editor, Uri } from 'monaco-editor-core';
 	import { loadGrammars, loadTheme, prepareVirtualFiles } from 'monaco-volar';
 	import { onMounted, ref } from 'vue';
 
@@ -36,10 +36,11 @@
 			// Prepare the virtual files.
 			prepareVirtualFiles();
 
+			const model = editor.createModel('<template>\n\t<div>Hello World</div>\n</template>', 'vue', Uri.parse('file:///demo.vue'))
+
 			// Create the editor.
 			const editorInstance = editor.create(monacoeditorcontainer.value, {
 				theme,
-				language: 'vue',
 				automaticLayout: true,
 				scrollBeyondLastLine: false,
 				minimap: {
@@ -48,7 +49,7 @@
 				inlineSuggest: {
 					enabled: false,
 				},
-				value: '<template>\n\t<div>Hello World</div>\n</template>',
+				model,
 			});
 
 			loadGrammars(editorInstance);
diff --git a/vite.config.ts b/vite.config.ts
index 53cedfd..69ff18d 100644
--- a/vite.config.ts
+++ b/vite.config.ts
@@ -4,8 +4,16 @@ import monacoEditor from 'vite-plugin-monaco-editor';
 
 // https://vitejs.dev/config/
 export default defineConfig({
+	optimizeDeps: {
+		include: ["path-browserify"]
+	},
+	resolve: {
+		alias: {
+			path: 'path-browserify'
+		}
+	},
 	plugins: [
 		vue(),
 		monacoEditor(),
-	],
+	]
 });
```

**Comment by Kingwl** [comment] 2022-07-11 08:03
Sorry. Misoperation.

**Comment by Kingwl** [comment] 2022-07-11 08:05
You can try 0.0.3 now.

**Comment by Kingwl** [comment] 2022-07-13 05:23
Hey! I wanna close this Issue if everything is working fine.

**Comment by dannysmc95** [comment] 2022-07-13 09:17
Hey @Kingwl sorry got busy and forgot to check it.

So looks like the error is gone, and that is awesome so big thanks for that, do I still need the `path-browserify` stuff that @johnsoncodehk referenced above?

Would it be okay if you just remove the debug code, etc from the package?
![image](https://user-images.githubusercontent.com/5339861/178697775-5084fd00-2d11-471b-999a-a17b58e536ac.png)

Lastly, what is your future plans for this package? I have some requirements for editing Vue components in the browser, so it would be great if you plan to expand this into something with more features like validation, type hinting, etc. As I can see that stuff isn't available yet - so just want to know where you plan to take the package.

Thanks again for your help, really appreciated.

**Comment by Kingwl** [comment] 2022-07-18 11:51
> Would it be okay if you just remove the debug code, etc from the package?

Sure.

> Is this a bug or just not implemented yet? (no scss highlighting).

Bug, I guess.

> Lastly, what is your future plans for this package?

Not yet, But you can send some issues to tell us what you want.

**Closed** 2022-07-19 06:20 UTC
